project:
  type: website

website:
  title: "CSD-stats"
  google-analytics: 
    tracking-id: "G-4YDRXVCBFQ"
    storage: "none"
    anonymize-ip: true
  navbar:
    search: true
    tools:
      - icon: github
        menu:
          - text: Contribute!
            href: https://github.com/rbcavanaugh/csd-stats/issues
          - text: Source Repository
            href:  https://github.com/rbcavanaugh/csd-stats
  
    
format:
  html:
    theme:
      dark: superhero
      light: cosmo
    toc: true