project:
  type: website

website:
  title: "Home"
  google-analytics: 
    tracking-id: "G-4YDRXVCBFQ"
    storage: "none"
    anonymize-ip: true
  navbar:
    left: 
      - text: "Learning R & Stats"
        href: learning-R.qmd
      - text: "Quant Methods"
        href: quant-methods.qmd
      - text: "Research, Writing, & Other Things"
        href: research-and-writing.qmd
    search: true
    tools:
      - icon: github
        menu:
          - text: Contribute!
            href: https://github.com/rbcavanaugh/csd-stats/issues
          - text: Source Repository
            href:  https://github.com/rbcavanaugh/csd-stats
    
format:
  html:
    theme:
      dark: superhero
      light: cosmo
    toc: true