---
format: html
toc: true
---

## Learning R

-   **psyTeachR**: https://psyteachr.github.io\* This is a set of resources and they are fantastic. Also for learning statistics. 

-   **R for Data Science**: https://r4ds.had.co.nz (Hadley Wickham and Garrett Grolemund - the standard)

-   **R for Reproducible Scientific Analysis by Software Carpentry**: https://swcarpentry.github.io/r-novice-gapminder. Step-by-step guide on introducing R and R-studio with the basic fundamentals. The information is pretty replicable to tutorials found in R for Data Science, but I found it slightly more approachable for novices (-Courtney Jewell).

-   **Workflow recommendations**: https://www.tidyverse.org/blog/2017/12/workflow-vs-script/, https://here.r-lib.org. These are not really R resources but these are things everyone should do when using R, so I'm just going to plug them here.

-   **How to ask for help**: https://reprex.tidyverse.org. When you're stuck on something and want to ask for help from someone, if you do it this way, you will get the most helpful response but also probably you will figure out why you're stuck halfway through doing this.

-   **Happy Git with R**: https://happygitwithr.com In case you want/need to also incorporate git into your workflow.

## General Statistics books

-   **Learning Statistics with R**: https://learningstatisticswithr.com\*

-   **Improving Your Statistical Inferences**: https://lakens.github.io/statistical_inferences/

-   **The Order of the Statistical Jedi: Responsibilities, Routines, and Rituals**:  https://quantpsych.net/stats_modeling\*

-   **Common statistical tests are linear models (or: how to teach stats)**: https://lindeloev.github.io/tests-as-linear/

-   **Statistical Rethinking**: http://xcelab.net/rm/ (2024 online lectures: https://github.com/rmcelreath/stat_rethinking_2024)\*

-   **Regression and other Stories**: https://avehtari.github.io/ROS-Examples/

-   **Introduction to Modern Statistics**: https://openintro-ims.netlify.app

-   **An introduction to statistical learning**: https://www.statlearning.com

-   Winter, B. (2019). **Statistics for linguists: An introduction using R.** Routledge. (https://appliedstatisticsforlinguists.org/bwinter_stats_proofs.pdf)

-   **Statistics of Dom**: https://statisticsofdoom.com

## Data Viz

-   Wilke, C. O. (2019). **Fundamentals of data visualization: a primer on making informative and compelling figures.** O'Reilly Media. https://clauswilke.com/dataviz/

-   Nordmann, E., McAleer, P., Toivo, W., Paterson, H., & DeBruine, L. M. (2022). **Data visualization using R for researchers who do not use R**. Advances in Methods and Practices in Psychological Science, 5(2), 25152459221074654.

-   Kabacoff, R. (2024). **Modern data visualization with R.** Chapman and Hall/CRC. https://rkabacoff.github.io/datavis/

-   Chang, W. (2018). **R graphics cookbook: practical recipes for visualizing data.** O'Reilly Media. https://r-graphics.org

-   **ggplot2 workshop** (Thomas Lin Pedersen) https://www.youtube.com/watch?v=h29g21z0a68

