---
format: html
toc: true
---

## Some bigger picture stuff

- Horoscopes (Richard McElreath), https://share.eva.mpg.de/index.php/s/9KEzTJg6oZ5dZZb
 
- Writing research questions: Peters, M.A.K. *How to develop good research questions.* Nat Hum Behav (2025). https://doi.org/10.1038/s41562-025-02292-5 (a.k.a., read...a lot)

- Scheel, A. M., Tiokhin, L., Isager, P. M., & Lakens, D. (2020). Why Hypothesis Testers Should Spend Less Time Testing Hypotheses. Perspectives on Psychological Science, 16(4), 744-755. https://doi.org/10.1177/1745691620966795 

## Writing about statistics

-   **Basic Statistical Reporting for Articles Published in Biomedical Journals: The “Statistical Analyses and Methods in the Published Literature” or The SAMPL Guidelines”** https://www.equator-network.org/wp-content/uploads/2013/03/SAMPL-Guidelines-3-13-13.pdf

-   **Guidance on Statistical Reporting to Help Improve Your Chances of a Favorable Statistical Review** https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7193848/pdf/rccm.202003-0477ED.pdf

- **Top tier guidance from a top rehab journal:** Lohse, Keith R. PhD, PStat; Kliethermes, Stephanie PhD. Approaching Significance: Statistical Guidance for Authors and Reviewers. Journal of Neurologic Physical Therapy ():10.1097/NPT.0000000000000526, July 16, 2025. | DOI: 10.1097/NPT.0000000000000526

## Common statistical errors I've come across in CSD research

- **Questionable interpretations of p-values** Anderson, S. F. (2020). Misinterpreting p: The discrepancy between p values and the probability the null hypothesis is true, the influence of multiple testing, and implications for the replication crisis. Psychological Methods, 25(5), 596–609. https://doi.org/10.1037/met0000248

- **Many of the other NHST myths:** Greenland, S., Senn, S. J., Rothman, K. J., Carlin, J. B., Poole, C., Goodman, S. N., & Altman, D. G. (2016). Statistical tests, P values, confidence intervals, and power: a guide to misinterpretations. European journal of epidemiology, 31(4), 337-350.

- **And questionable reporting of p-values** - https://mchankins.wordpress.com/2013/04/21/still-not-significant-2/

- **The Difference Between “Significant” and “Not Significant” is not Itself Statistically Significant. Often known as, 'yes you do need that interaction in your model'.** - http://www.stat.columbia.edu/\~gelman/research/published/signif4.pdf

- **Failing to report contrast coding or incorrect interpretation of contrasts** Brehm, L., & Alday, P. M. (2022). Contrast coding choices in a decade of mixed models. Journal of Memory and Language, 125, 104334. https://doi.org/10.1016/j.jml.2022.104334

- **A long list of common statistical myths**: https://discourse.datamethods.org/t/reference-collection-to-push-back-against-common-statistical-myths/1787

- Liddell, T. M., & Kruschke, J. K. (2018). **Analyzing ordinal data with metric models: What could possibly go wrong?.** Journal of Experimental Social Psychology, 79, 328-348. and https://media.dlib.indiana.edu/media_objects/mp48sh50s

- **The Table 2 Fallacy**: Westreich, D., & Greenland, S. (2013). The table 2 fallacy: presenting and interpreting confounder and modifier coefficients. American journal of epidemiology, 177(4), 292-298.


## Data Management, Open Science & Reproducibility

- **A great resource with lots of information that could in many sections on this site**. Frank, M. C., Braginsky, M., Cachia, J., Coles, N. A., Hardwicke, T. E., Hawkins, R. D., Mathur, M. B., & Williams, R. 2025. Experimentology: An Open Science Approach to Experimental Psychology Methods. Stanford University. https://doi.org/10.25936/3JP6-5M50. (Also published by MIT Press, ISBN 978-0-262-55256-1). free at: https://experimentology.io. 

- Lewis, C. (2024). **Data Management in Large-Scale Education Research (1st ed.)**. Chapman and Hall/CRC. https://doi.org/10.1201/9781032622835 (free at: https://datamgmtinedresearch.com)

-   Strand, J. F. (2023). **Error tight: Exercises for lab groups to prevent research mistakes.** Psychological Methods.

-   Brown, V. A., & Strand, J. F. (2023). **Preregistration: Practical Considerations for Speech, Language, and Hearing Research.** Journal of Speech, Language, and Hearing Research, 66(6), 1889-1898.

-   **Stanford Psychology guide to doing open science:** https://poldrack.github.io/psych-open-science-guide/4_reproducibleanalysis.html

-   **The Turing Way:** https://book.the-turing-way.org

-   Alston, J. M., & Rick, J. A. (2021). **A beginner’s guide to conducting reproducible research.** Bulletin of the Ecological Society of America, 102(2), 1-14.

## Blogs & Podcasts & People to follow on Socials (please add more!)

For me, a good blog post is the necessary on ramp to actually understanding a statistics paper and implementing an approach with my own data. Many of these writers/researchers are fantastic at distilling complex ideas into short(ish) blog posts that almsot anyone can understand.

-   **Quantitude**: https://quantitudepod.org

-   **Solomon Kurz**: https://solomonkurz.netlify.app/blog/

-   **Andrew Heiss**: https://www.andrewheiss.com/blog/

-   **Danielle Navarro**: https://djnavarro.net

-   **Julia Rohrer & colleagues**: https://www.the100.ci

-   **Allison Horst**: https://allisonhorst.com

-   **Richard McElreath**: https://xcelab.net/rm/

-   **Jamie Reilly**: https://www.reilly-coglab.com/reilly

-   **Shravan Vasishth**: https://vasishth.github.io

-   **Julia Silge**: https://juliasilge.com/blog/

-   **Lisa Debruine**: https://debruine.github.io

-   **TJ Mahr**: https://www.tjmahr.com/year-archive/

-   **Michael Clark**: https://m-clark.github.io/code.html

-   **Daniel Lakens**: http://daniellakens.blogspot.com

-   **Gavin Simpson**: https://fromthebottomoftheheap.net

-   **Andrew Gelman**: https://statmodeling.stat.columbia.edu

-   **Kieran Healy**: https://kieranhealy.org

-   **Kristoffer Magnusson**: https://rpsychologist.com/posts

## Workshops (please add more!)

-   https://debruine.github.io/data-sim-workshops/

-   https://smart-workshops.com

-   https://centerstat.org

-   https://causalab.sph.harvard.edu/courses/

-   Annual statistics summer school: https://vasishth.github.io

